export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_TO_CART = 'REMOVE_TO_CART'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

export const RECEIVE_PRESTATIONS = 'RECEIVE_PRESTATIONS'
export const REQUEST_PRESTATIONS_ERROR = 'RECEIVE_PRESTATIONS'

export const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS'

export const ADD_APPOINTMENT_DATE = 'ADD_APPOINTMENT_DATE'
